# Generated by Django 4.2.11 on 2024-06-30 13:10

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='MetaGlobal',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('regular_menu', models.JSONField()),
                ('mega_menu', models.JSONField()),
                ('uncategorized_footer', models.JSONField()),
                ('categorized_footer', models.JSONField()),
                ('logo', models.ImageField(upload_to='')),
                ('metadata', models.JSONField()),
            ],
        ),
    ]
