# Generated by Django 4.2.11 on 2024-05-26 05:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('order', '0004_alter_order_currency_alter_order_customer_currency'),
    ]

    operations = [
        migrations.AlterField(
            model_name='order',
            name='total_price_in_customer_currency',
            field=models.DecimalField(blank=True, decimal_places=4, help_text="Original amount paid by the customer in the customer's currency, stored in cents. ", max_digits=12, null=True),
        ),
    ]
