# Generated by Django 4.2.11 on 2024-05-29 19:14

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('order', '0007_orderlineitem_currency_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='order',
            name='total_price',
            field=models.BigIntegerField(blank=True, help_text="Total amount of the order in cents, converted from the original currency (customer's currency) to the base currency. For example, if the base currency is USD and the customer_currency is different (e.g., AUD), the total amount will be converted to USD. This converted amount is stored in cents.", null=True, validators=[django.core.validators.MinValueValidator(1)]),
        ),
    ]
