# Generated by Django 4.2.11 on 2024-05-27 09:24

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0003_alter_currencyexchange_exchange_rate'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='currencyexchange',
            options={'ordering': ('-last_modified',)},
        ),
        migrations.AlterUniqueTogether(
            name='currencyexchange',
            unique_together={('base_currency', 'target_currency')},
        ),
    ]
