# Generated by Django 4.2.11 on 2024-05-27 16:30

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0004_alter_currencyexchange_options_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='sitesettings',
            name='timezone',
        ),
    ]
