# Generated by Django 4.2.11 on 2024-05-27 05:02

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('product', '0003_productvariant_currency'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='product',
            name='currency',
        ),
    ]
