# Generated by Django 4.2.11 on 2024-06-30 18:56

from django.db import migrations, models
import django.db.models.deletion
import nxtbn.core.models


class Migration(migrations.Migration):

    dependencies = [
        ('filemanager', '0002_initial'),
        ('product', '0004_alter_color_name'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='product',
            name='media',
        ),
        migrations.AddField(
            model_name='product',
            name='images',
            field=models.ManyToManyField(blank=True, to='filemanager.image'),
        ),
        migrations.AddField(
            model_name='product',
            name='internal_metadata',
            field=models.JSONField(blank=True, default=dict, null=True, validators=[nxtbn.core.models.no_nested_values]),
        ),
        migrations.AddField(
            model_name='product',
            name='metadata',
            field=models.JSONField(blank=True, default=dict, null=True, validators=[nxtbn.core.models.no_nested_values]),
        ),
        migrations.RemoveField(
            model_name='productvariant',
            name='variant_image',
        ),
        migrations.AddField(
            model_name='productvariant',
            name='variant_image',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='filemanager.image'),
        ),
    ]
