# Generated by Django 4.2.11 on 2024-05-27 09:24

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('product', '0005_alter_product_options'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='product',
            options={'ordering': ('name',)},
        ),
        migrations.AlterModelOptions(
            name='productvariant',
            options={'ordering': ('price',)},
        ),
    ]
