# Generated by Django 4.2.11 on 2024-06-30 05:42

from django.db import migrations, models
import nxtbn.core.models


class Migration(migrations.Migration):

    dependencies = [
        ('product', '0006_alter_product_options_alter_productvariant_options'),
    ]

    operations = [
        migrations.AddField(
            model_name='productvariant',
            name='internal_metadata',
            field=models.JSONField(blank=True, default=dict, null=True, validators=[nxtbn.core.models.no_nested_values]),
        ),
        migrations.AddField(
            model_name='productvariant',
            name='metadata',
            field=models.JSONField(blank=True, default=dict, null=True, validators=[nxtbn.core.models.no_nested_values]),
        ),
    ]
