# Generated by Django 4.2.11 on 2024-06-14 13:12

from django.db import migrations, models
import nxtbn.plugins.models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Plugin',
            fields=[
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('last_modified', models.DateTimeField(auto_now=True)),
                ('name', models.CharField(max_length=255, primary_key=True, serialize=False, unique=True, validators=[nxtbn.plugins.models.validate_plugin_name])),
                ('description', models.TextField(blank=True, null=True)),
                ('path', models.FilePathField(allow_folders=True, path='nxtbn/plugins/sources/')),
                ('plugin_type', models.CharField(choices=[('PAYMENT_PROCESSOR', 'Payment Processor'), ('CURRENCY_BACKEND', 'Currency Backend'), ('GENERAL', 'General')], default='GENERAL', max_length=20)),
                ('is_active', models.BooleanField(default=True)),
                ('home_url', models.URLField(blank=True, null=True)),
                ('documentation_url', models.URLField(blank=True, null=True)),
            ],
            options={
                'abstract': False,
            },
        ),
    ]
