# Generated by Django 4.2.11 on 2024-06-19 10:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('plugins', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='plugin',
            options={'ordering': ('name',)},
        ),
        migrations.AddField(
            model_name='plugin',
            name='has_deleted',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='plugin',
            name='plugin_type',
            field=models.CharField(choices=[('PAYMENT_PROCESSOR', 'Payment Processor'), ('CURRENCY_BACKEND', 'Currency Backend'), ('SMS_SERVICE', 'SMS Service'), ('EMAIL_SERVICE', 'Email Service'), ('GENERAL', 'General')], default='GENERAL', max_length=20, unique=True),
        ),
        migrations.AlterUniqueTogether(
            name='plugin',
            unique_together={('name', 'plugin_type')},
        ),
    ]
