# Generated by Django 4.2.11 on 2024-06-20 09:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('plugins', '0002_alter_plugin_options_plugin_has_deleted_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='plugin',
            name='is_default',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='plugin',
            name='tag',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='plugin',
            name='plugin_type',
            field=models.CharField(choices=[('PAYMENT_PROCESSOR', 'Payment Processor'), ('CURRENCY_BACKEND', 'Currency Backend'), ('SMS_SERVICE', 'SMS Service'), ('EMAIL_SERVICE', 'Email Service'), ('INVOICE', 'Invoice'), ('GENERAL', 'General')], default='GENERAL', max_length=20, unique=True),
        ),
    ]
